service: chat_group_websocket

plugins:
  - serverless-offline
provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs12.x
  stage: dev

functions:
  connect:
    events:
      - websocket:
          route: $connect
    handler: handler.connectHandler

  disconnect:
    events:
      - websocket:
          route: $disconnect
    handler: handler.disconnectHandler

  default:
    events:
      - websocket:
          route: $default
    handler: handler.defaultHandler

  api:
    handler: handler.expressHandler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY